feat: check dependencies before use

diff --git a/notflix b/notflix
--- a/notflix
+++ b/notflix
@@ -1,6 +1,24 @@
 #!/bin/sh
 
-# Dependencies - webtorrent, mpv
+dependencies="dmenu notify-send curl mpv webtorrent"
+
+die() {
+	printf "notflix: %s\n" "$@" >&2
+	exit 1
+}
+
+is_installed() {
+	which "$1" 2>/dev/null>&2
+}
+
+check_dependencies() {
+	for dependency in $dependencies; do
+		is_installed "$dependency" || 
+			die "$dependency is required to run this script, but it is not installed"
+	done
+}
+
+check_dependencies
 
 mkdir -p $HOME/.cache/notflix
 
